### ISSUE TITLE
cli push: source strings not updated after str change

### ISSUE THREAD

**Issue by jdewit** [transifex/transifex-javascript#104]
Hi!

I am using the cli (2.1.2) in an angular 12 project to extract keys and push them to transifex. 

`txjs-cli push some-feature/ <secrets>`

New keys are uploaded just fine.

However, if I change the 'str' value of a translation, the changes are not picked up and nothing is updated. 

This is the case for pipes and the T directive.

Ex.

`      <T
        str="Hello"
        key="hello_text"
        tags="some-tag"
      ></T>`

cli push creates the key

`      <T
        str="Hello there"
        key="hello_text"
        tags="some-tag"
      ></T>`

cli push says nothing was updated. Logging into transifex shows no change as well. 

Side note: If I change the key, it is picked up and a new key is created as expected.

**Comment by nbasili** [comment]
@jdewit Can try to push again through the `txjs-cli` by also adding the `--purge` flag?

Just make sure that you are NOT sharing the same Transifex Native project with another code repo, as the `purge` flag will **destroy** any other strings pushed outside your current Angular project.

**Comment by jdewit** [comment]
adding the --purge option creates a new string as expected.

Ideally we only want to push translation changes for files that are changed in a commit though. A purge would be done once in awhile since scanning the entire project takes a very long time.

**Comment by nbasili** [comment]
@jdewit We have updated the API endpoint for pushing strings to support updating the source string of existing keys. It should be working now as you requested, without any change required from your side.

Can you please check if it works on your project and close the issue?
