### ISSUE TITLE
Remove or pin "colors" dependency for transifex-cli

### ISSUE THREAD

**Issue by gbyesiltas** [transifex/transifex-javascript#111]
`transifex-cli` has a dependency on the "colors" package with the version being `^1.4.0`. However, there is a vulnerability in the colors package starting from version `1.4.1`.

Related: https://snyk.io/blog/open-source-npm-packages-colors-faker/

**Comment by codegaze** [comment]
Hey @gbyesiltas, your contribution is much appreciated. 💪
I already merged your PR and version `v2.3.1` should include the fix.

**Comment by gbyesiltas** [comment]
Thank you!
