### ISSUE TITLE
[Question] Purge behavior when source string change on Transifex

### ISSUE THREAD

**Issue by rothlis** [transifex/transifex-javascript#115]
Hello team!

I'm testing the behavior of the purge option and came across something strange.

Let's say that the CLI extract `I'm a FOO string` from the code and generates this hash key `6a0cefc0b1d758b413e6b07bc3c7c28f` (using `--key-generator=hash`).

```
└─ 6a0cefc0b1d758b413e6b07bc3c7c28f: I'm a FOO string
```

Imagine the content team edits on Transifex the source string to `I'm a BAR string`. The key is still `6a0cefc0b1d758b413e6b07bc3c7c28f` in the UI.

However, when we push again using the `--purge` option, although the generated hash key is still `6a0cefc0b1d758b413e6b07bc3c7c28f` the CLI deletes and recreates the string, thus losing the `I'm a BAR string` edit.

So my question is, does the purge option work on the string key or the string content?

---
We are using Transifex Native and the CLI version `@transifex/cli/2.3.1 darwin-x64 node-v14.17.5`

**Comment by rothlis** [comment]
FYI, same behavior when testing with a custom `_key`. So it looks like the purge is not comparing keys but string content?

**Comment by nbasili** [comment]
Nice catch @rothlis. We just fixed this in the CDS code [here](https://github.com/transifex/transifex-delivery/pull/43).
Can you give it another shot?

**Comment by rothlis** [comment]
Looking good now @nbasili! Thanks for the quick fix!
