### ISSUE TITLE
[Bug] `useTranslations` is not exported from `@transifex/react`

### ISSUE THREAD

**Issue by kfazinic** [transifex/transifex-javascript#118]
**Current Behavior**
Type definition for [`useTranslations`](https://developers.transifex.com/docs/react-sdk#usetranslations-hook---aka-lazy-loading) is missing in @transifex/react. 

**Expected Behavior**
`useTranslations` is fully typed

**Comment by codegaze** [comment]
Hey, @kfazinic nice catch! 

We just released a new version `v2.3.2` that should fix this issue. Please feel free to test it out and close this.

**Comment by kfazinic** [comment]
@codegaze that was fast, thanks! 🙌
