### ISSUE TITLE
Using single transifex project in multiple react repos

### ISSUE THREAD

**Issue by shaaandi** [transifex/transifex-javascript#122]
With latest transifex/native version we can use multiple project instances by using react context.
However, it is very cubmersome and also adds much more work.

For example, let’s say we have a component ComponentA
```
export const ComponentA = ({ children }) => (
  <div>
   <T _str="Just adding something here" />
  {children}
 </div>
)
```
and now I want to use this component in another repo 100 times. And so now, I need to do

/ * this code is in the main repo */
```
<Header>
  <TxProvider instance={ComponentALibraryInstance}>
     <ComponentA>
         <TxProvider instance={RootLibraryInstanceCopy}>
            <T _str="Some string on main repo />
         <TxProvider />
    <ComponentA />
 <TxProvider />
<Header />
```
You can see that I don’t want to do this 100 times in my code base. Plus, what that is just a simple use-case.
Imagine a component which takes like 10 props of type ReactNode. This means wrapping all of them with contexts.

**How to use a single shared project across multiple repos.**

We can easily solve this issue by just using a single project across all repos, But then we can’t --purge anymore as pushing from projectA will result in losing the strings from projectB and so on.

The above is my current knowledge.
What I am really looking for ?
Is there any way to use a single native project across multiple repos and also being able to remove unsused strings across all projects ? – we can do it using monorepo, but my concern is doing it across multiple project repos.
I see we do have some tagging system but not sure how to relative them all in a sense where you can acheive the --purge behaviour across multiple repos.

Thanks

Related community discussions:
https://community.transifex.com/t/using-single-transifex-project-in-multiple-react-repos/2714
https://community.transifex.com/t/using-multiple-transifex-projects-in-react-app/2595 (Previous solution using context)

**Comment by egilkh** [comment]
Hey!

Here is what I've ended up doing: tags.

I only have 2 repos/codebases but I tag each one with it's own name. Example: `projectA` and `projectB`. This leaves each codebase with its own tags but the strings are shared. So change in translation is correct.

And you can purge / delete all that has one tag, meaning you can wipe one codebase without affecting the others.

The problem now arises over time in that you'll end up with not doing any big `--purge`, and to solve this I've started adding a third tag when pushing which is the year and month. Example `202203`. Now I can select and delete based on the fact that any old string will not have the new year and month tag. 

When to do a purge like this now becomes a job that is a bit harder, but manageable. Disclaimer: I only have 2 codebases that share the same Transifex project. So for me it is quite manageable. 

For our use case it is decent, some scruffy old strings that needs to be deleted over time. I imagine it might increase cost a bit but it sure does same me some headaches.

**Comment by nbasili** [comment]
We are using something similar in Transifex, where we share the same Native project between Django (python) and React pages (Javascript). We have assembled a guide to explain the process: https://developers.transifex.com/docs/cleaning-up-native-resources
