### ISSUE TITLE
[Bug] api returns "f [Error]: 2" rather than the actual 404 response 

### ISSUE THREAD

**Issue by Foda** [transifex/transifex-javascript#123]
**Current Behavior**
If API is used to fetch all resources, or used to fetch a resource translation from a resource they're not a translator on (but still part of the org/project), the API will return a very unhelpful `f [Error]: 2` without any other details.

In order to find what the "real" error was, I had to use the [online interactive API docs](https://developers.transifex.com/reference/get_resource-translations), which revealed the real error (which is also incorrect):
```
"status": "404",
"code": "not_found",
"title": "Object not found",
"detail": "No `ProjectLanguage` resource found with the identifier `p:xxx:l:xxx`"
```

**Expected Behavior**
The error returned should indicate that the user doesn't have permission/is not a translator for the requested language.

**Steps to Reproduce**
Using the latest `@transifex/api` package:

Scenario 1:
```
const { transifexApi } = require('@transifex/api');

const project = await transifexApi.Project.get({ organization: `o:${org_slug}`, slug: project_slug });
const resources = await project.fetch('resources');
const resource = await resources.get({ slug: resource_slug }); // *** Error thrown here ***
```

Scenario 2:
```
const { transifexApi } = require('@transifex/api');

const language = await transifexApi.Language.get({ code: 'es' });
filter = { resource: ..., language };
for await (const t of transifexApi.ResourceTranslation // *** Error thrown here ***
      .filter(filter)
      .include('resource_string')
      .all()) {
```

**Possible Solution**
API should expose the real HTTP error. Additionally, a 404 error should only be returned if the resource doesn't actually exist as per the HTTP spec, and should not be used if the user does not have the correct translator status.

**Comment by nbasili** [comment]
@Foda We released version `3.0.0` that has more verbose errors exposed. I hope it fulfils the requirements of this issue. 

Related PR: #124
