### ISSUE TITLE
[Bug] api ResourceTranslationsAsyncDownload.download() sometimes throws getaddrinfo ENOTFOUND error 

### ISSUE THREAD

**Issue by seotts** [transifex/transifex-javascript#127]
**Current Behavior**
When downloading resource translations, `ResourceTranslationsAsyncDownload.download()` sometimes throws a getaddrinfo ENOTFOUND error. I often see this after many downloads (say, over 1000), but not after a consistent number of downloads or for a consistent language or resource (it changes every time.) After the first failed download, some subsequent downloads succeed while others fail in the same way.

From the error message, it seems like this failure might be happening during the download status check step of `download()`.

Excerpt of the error message:
```
Error: getaddrinfo ENOTFOUND rest.api.transifex.com
at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26) {
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'rest.api.transifex.com',
  config: {
    [...]
    url: 'https://rest.api.transifex.com/resource_translations_async_downloads/20cbdc15-ce1d-4c5c-bb53-bbf25e1ffed7',
    maxRedirects: 0,
    method: 'get',
    params: null,
    data: undefined
  }
[...]
}
```

**Expected Behavior**
I'd expect download to return a url, or, in case of failure an error that I can take action on (such as a 429 if this is a rate limiting problem.)

**Steps to Reproduce**
Run this for a large list of resources and languages:
```
const url = await transifexApi.ResourceTranslationsAsyncDownload.download({
        mode,
        resource,
        language
    });
```

**Comment by nbasili** [comment]
@seotts Googled a bit about the issue and it may be related to NodeJS. Internally the package is using `axios`. 

Can you share which Node version you are using? 
Also, are you doing all these requests in parallel (e.g. using Promise.all), or sequentially one at a time?

Maybe using [axios-retry](https://www.npmjs.com/package/axios-retry) internally in the package would fix the issue.

**Comment by nbasili** [comment]
@seotts It's been a while, but do you still encounter this issue? In the meantime we have improved the throughput of the async downloads on the APIv3 side.
