### ISSUE TITLE
[Bug] infinite retry for 202 http status

### ISSUE THREAD

**Issue by ianweng** [transifex/transifex-javascript#137]
**Current Behavior**
The localisation hangs when keep getting 202.

![image](https://user-images.githubusercontent.com/13402148/169685387-ee2922c2-7b77-4bcc-8499-a3619433a274.png)

**Expected Behavior**
Do not hang forever for 202.

**Steps to Reproduce**
Use this lib when transifex is in maintenance for long.

**Possible Solution**
An infinite retry for http status code 202 was introduced in https://github.com/transifex/transifex-javascript/pull/20.
Add a max retry limit.

**Comment by nbasili** [comment]
@ianweng Thanks for reporting the issue. It is indeed valid and we are making the following steps to remediate it. The first fix is on the CDS service. We applied [this patch](https://github.com/transifex/transifex-delivery/pull/54) and we released CDS `2.2.0` that will properly stop the `202` http status code from looping forever.

We will also release an update on the JS SDK, where you can set some additional settings to control a timeout behaviour. PR will be opened soon. Will keep you posted in this thread.

**Comment by nbasili** [comment]
And, this is the [@transifex/native v4.2.0 release](https://github.com/transifex/transifex-javascript/releases/tag/v4.2.0) that adds support for timeouts on the SDK.

**Comment by nbasili** [comment]
One more feature planned, that will also help CDS to have 100% uptime, even when Transifex is down, is to automatically invalidate or warm-up CDS, when a new translation is added or updated on Transifex TMS. 

This way, TMS can do a "push" event to the CDS, to invalidate the content automatically, and ensure that there are always translations available to be served to the end-users via the SDK. This can alleviate the `202 http` status codes once and for all, unless the developer decides to manually purge the CDS cache.

**Comment by nbasili** [comment]
Today we released an automatic auto-CDS cache invalidation, whenever a new translation or source edit is happening on Transifex. This works only for the Transifex hosted CDS.

**Comment by ianweng** [comment]
Thank you for actioning on this so quickly! @nbasili
