### ISSUE TITLE
Vue3 Support?

### ISSUE THREAD

**Issue by shtse8** [transifex/transifex-javascript#146]
Does transifex supprt vue3? I want to give it a try but cannot find vue3 package.

**Comment by nbasili** [comment]
No it does not, but it is on our radar to add one, given that we have enough interest. So your comment is adding up to that case :)

**Comment by StewPoll** [comment]
I'd love to add my support to this as well.

**Comment by codegaze** [comment]
Hello @shtse8, @StewPoll!

We have some good news! 

Today we released a new major version of Native ([v5.0.0](https://github.com/transifex/transifex-javascript/releases/tag/v5.0.0)) with a lot of improvements and a new [Vue3](https://github.com/transifex/transifex-javascript/tree/master/packages/vue3) plugin 
so Vue3 is now supported in the Transifex Native ecosystem! 🎉

**Comment by StewPoll** [comment]
Glorious news @codegaze , thanks for the update.
