### ISSUE TITLE
Imported Tags Ignored by txjs-cli

### ISSUE THREAD

**Issue by aarr0n** [transifex/transifex-javascript#149]
I've a use case where I'm wanting to store tags in a constant and import / use that in different components, but its not being recognised by `txjs-cli`. 

When I run `txjs-cli push` the tags are not present in the output (using the `verbose` argument) and they don't appear in Transifex. But, if I define the `const` within the component file the tags are registered.

## This does not work

**constants.ts**

```ts
export const MY_TAGS = 'tag1,tag2'

```

**component.tsx**

```tsx
import { T } from '@transifex/react'
import { MY_TAGS } from './constants.ts'
// ...
<T _str="EXAMPLE" _tags={MY_TAGS} />
```

## This does work

**component.tsx**

```tsx
import { T } from '@transifex/react'

const MY_TAGS = 'tag1,tag2'

// ...
<T _str="EXAMPLE" _tags={MY_TAGS} />
```

**Comment by nbasili** [comment]
The CLI tools does not resolve imports, so this will not work. Parsing happen on a local file level looking for `t` or `<T>` tags and resolving local variables. Something that maybe you can do instead is append tags using the command line:
```
txjs-cli push src/components/ --append-tags="tag1,tag2"
```
