### ISSUE TITLE
Strings don't update [Bug]

### ISSUE THREAD

**Issue by localjo** [transifex/transifex-javascript#150]
**Current Behavior**
Strings are not updated in web dashboard after running push.

**Expected Behavior**
Strings should be updated (added or changed).

**Steps to Reproduce**
Run `txjs-cli push '{,!(node_modules|dist)/**/}*.{js,jsx,ts,tsx}' --token=$TRANSIFEX_TOKEN --secret=$TRANSIFEX_SECRET`
or `txjs-cli push '{,!(node_modules|dist)/**/}*.{js,jsx,ts,tsx}' --token=$TRANSIFEX_TOKEN --secret=$TRANSIFEX_SECRET --purge`

Output:

```
Parsing all files to detect translatable content...
⸨████████████████████████████████████████⸩ 50/50 /webpack.config.js
✓ Processed 50 file(s) and found 46 translatable phrases.
✓ Content detected in 3 file(s).

Uploading content to Transifex... Success
✓ Successfully pushed strings to Transifex:
  Skipped strings: 46
```

**Possible Solution**
It seems that the CLI doesn't thing there are any new strings, so skips everything. But there are three new strings which are not yet in the dashboard and available for translation. Alternatively, the strings did get uploaded but there is some sort of cache blocking them from showing.

**Comment by localjo** [comment]
I also tested by adding another new string, and I get the following output:

```
Parsing all files to detect translatable content...
⸨████████████████████████████████████████⸩ 50/50 /webpack.config.js
✓ Processed 50 file(s) and found 47 translatable phrases.
✓ Content detected in 3 file(s).

Uploading content to Transifex... Success
✓ Successfully pushed strings to Transifex:
  Created strings: 1
  Skipped strings: 46
```

I think the 3 strings I had added before must have had similar output that I didn't notice. But this new "created string" doesn't show up anywhere in the Transifex dashboard for my project.

**Comment by localjo** [comment]
Another thing I tried was running `txjs-cli invalidate --token=$TRANSIFEX_TOKEN --secret=$TRANSIFEX_SECRET`, which output:

```
Invalidating CDS cache... Success
3 records invalidated
Note: It might take a few minutes for fresh content to be available
```

But after several minutes, there is no change in the content on the Transifex website.

**Comment by codegaze** [comment]
Hello @localjo,

From what you described, I assume what you should have in your project is 47 strings (46 + one new string). 
Could you please please make sure that the new string isn't in your resource?

The `invalidate` command is to invalidate the cache your application uses.

**Comment by localjo** [comment]
As I said, I checked the resource on the Transifex website, and the new string is nowhere to be found. I've been refreshing the dashboard for hours assuming it must be some sort of cache issue, but I'm still not seeing the new strings in the resource.

**Comment by codegaze** [comment]
@localjo Could you please share:

* The code you use to mark the string, along with the string
* Your organization, project and resource?

If these cannot be shared publicly, I would suggest contacting our Customer Support so they can help with what might be going on.

**Comment by localjo** [comment]
I am not finding the strings for the following code snippets in the Transifex dashboard.

```
// src/maps/map_graphic_config.js
t('FALL WARMING')
```

```
// src/line_chart/LineChart.js
if (variable && variable.startsWith('days_above_')) {
  return t('{more}Warm {seasonName} Days', {
    seasonName: LineChart.getSeasonName(season),
    more: this.trendDiff > 1 ? t('More ') : '',
  });
}

...

isF ? t('Temperatures shown in °F. ') : ''

```

The organization/project is: `climate-central/realtime-graphics` and the resource is Realtime Graphics. Of note: since the last time we uploaded strings, our repo's file structure has been reorganized, so it's possible that all of the strings should be updated, even though most of them are the same text as before, but I'm not seeing any changes to the other strings either.

**Comment by codegaze** [comment]
Thanks for the information @localjo. Now I can understand what happened, there is no technical issue with the library.

You have two Native projects and each project has its own credentials which relate to this project. You have been pushing strings to your other Native project and not `realtime-graphics`. You need to push to Transifex with the credential for this project.

I hope this solves the issue. :)

**Comment by codegaze** [comment]
Hey @localjo I assume everything is ok, so I will close this one. You can reopen it if you something is not working as it should.
