### ISSUE TITLE
Update useT hook to provide stable instance of `t` 

### ISSUE THREAD

**Issue by unkillbob** [transifex/transifex-javascript#154]
Currently the `useT` hook returns a new instance of the `t` function every time it is invoked.

It would be really useful if internally the `useT` hook wrapped the `t` function in a `useCallback` so that it always returned the same instance of the `t` function unless either the locale changes or translations are loaded (i.e. the same conditions that trigger a re-render by updating some state internally in `useT`). This would allow the `t` function to be "watched" by other useEffect/useCallback/useMemo hooks where for example there is some complex logic to produce some user facing strings that we only want to-rerun when the language changes or translations are loaded.

I'm happy to submit a PR if this is something you see that might be possible/helpful.

**Comment by nbasili** [comment]
This improvement is part of [4.3.0](https://github.com/transifex/transifex-javascript/releases/tag/v4.3.0) release. Thanks for the suggestion 🙏
