### ISSUE TITLE
i18next backend plugin loading resources after init

### ISSUE THREAD

**Issue by Bailig** [transifex/transifex-javascript#167]
Hi guy, I'm using i18next backend plugin in a react app. The issue I'm having is the backend plugin always fetches aall resources on init. I can use the filter tags to filter the ones required on all pages.

```typescript
const txBackend = new TransifexI18next({
  token: import.meta.env.TRANSIFEX_TOKEN,
  filterTags: "layout",
});
```

However, it seems like there's no easy way to load other tags after init. Something like `loadTags(["home"])`?

**Comment by nbasili** [comment]
Maybe you can try using [Lazy loading](https://developers.transifex.com/docs/javascript-sdk-content-splitting#lazy-loading) like this:
```
const txBackend = new TransifexI18next({
  token: import.meta.env.TRANSIFEX_TOKEN,
  filterTags: "layout",
});

...

txBackend.tx.fetchTranslations(txBackend.tx.getCurrentLocale(), {
  filterTags: "home",
});
```

**Comment by nbasili** [comment]
Closing this, feel free to re-open it if needed.
