### ISSUE TITLE
Translated strings used as variables are not being translated.

### ISSUE THREAD

**Issue by cichyadam** [transifex/transifex-javascript#172]
**Current Behavior**
So I currently have a bunch of languages defined as strings to translate in my `translations.ts` file looking like this: 

```
// src/translations.ts
import { t } from '@transifex/native'

t('English')
t('Danish')
t('Swedish')
```
These strings are correctly translated in our transifex platform. 

Then in my React component I have a string which I want to translate and use a variable in the string, variable which is dynamic and comes from backend response. 

```
// src/SomeTranslateButton.ts
import { t } from '@transifex/native'
...
...
...
<Button>

   {t('Translate to {language}', {  language } )} // Where language variable can be 'English', 'Danish' or 'English'
</Button>
```

This results in some weirdness, because the `language` variable is not being translated properly. So, when in English it's "Translate to English" but when using danish language it's "Oversæt til English" instead of "Oversæt til Engelsk" even though all the strings are translated in transifex.

It's the same result if I would for example try to use the T component from `@transifex/react`.

**Expected Behavior**
Expected Behavior is that the variable which is dynamic and it's already translated in our transifex project should be also translated on time with use of transifex package.

**Steps to Reproduce**
I have included some code examples above.

**Comment by nbasili** [comment]
The fix you provided is the correct way to handle this case. 🎯

The SDK will not translate the variables, because variables could be anything, from usernames, to numbers etc. Your approach to translate the variable is what you should actually do.
