### ISSUE TITLE
ErrorPolicy Not Handling Empty Strings

### ISSUE THREAD

**Issue by aarr0n** [transifex/transifex-javascript#176]
When attempting to push an empty string to a Transifex project using `txjs-cli` we correctly receive an error stating `"string" is not allowed to be empty`. 

However there is no way to know this during development since empty strings do not cause an error to be thrown and so are not picked up by a provided [errorPolicy](https://github.com/transifex/transifex-javascript/blob/master/packages/native/README.md?plain=1#L152). 

Could this be handled within [translateLocale](https://github.com/transifex/transifex-javascript/blob/master/packages/native/src/TxNative.js#L110) method of txNative - where an error is thrown when an empty string is detected?

**Comment by nbasili** [comment]
Do you think it makes sense to do the opposite? Update `txjs-cli` to ignore empty strings during push?

**Comment by aarr0n** [comment]
> Do you think it makes sense to do the opposite? Update `txjs-cli` to ignore empty strings during push?

Yeah that would also work (we've since introduced a lint rule to guard against this).
