### ISSUE TITLE
[Bug] Cli push doesn't recognize key and tags in the translate pipe when there are variables defined using pipes

### ISSUE THREAD

**Issue by mgrilec** [transifex/transifex-javascript#177]
**Current Behavior**
The cli push doesn't recognize the key and tags.

**Expected Behavior**
Cli push should recognize key and tags.

**Steps to Reproduce**
Have somewhere in your HTML

```
"{{ '{var1}' | translate:{ _key: 'some-key', _tags: 'some tags', var1: someDate | date: 'dd.MM.yyyy' } }}"
```

```
txjs-cli push
```

**Possible Solution**
??

**Possible Implementation**
The translate params are read by passing the whole params object to ``Function(`"use strict";return (${obj})`)();``, which doesn't parse well. The key, tags and all other predefined keys should be parsed using a regex with a capturing group. Other params are not useful for the parser anyway.

**Comment by pablotransifex** [comment]
Hello @mgrilec and thank you for referring this parsing issue. The truth is that the Angular pipe lacks of good parsing, when no references to variables are in place, the tags are recognized and pushed, but when in the parameters are references to variables, we cannot understand using a simple parsing, and thus the parameters are ignored (all).

I try to minimize the side effects in this [PR](https://github.com/transifex/transifex-javascript/pull/180).

Let's wait for the reviews and when deployed, give it a try.

**Comment by mgrilec** [comment]
> NOTE: For the translate pipe parameters, is better to use quotes for delimiting the string values, otherwise the results are unexpected.

It's not possible to use double quotes in cases where the pipe has to be used inside attributes.

```
<input placeholder="'Password' | translate : { _key: 'password' }"
```

What do you suggest to use there?

**Comment by pablotransifex** [comment]
Hello @mgrilec I will look into it,, I think the regex for these specific syntax has some problem. I'll try to find a fix ASAP.

Thank you for the feedback!

**Comment by pablotransifex** [comment]
@mgrilec Have you tested this one with the latest release?

**Comment by pablotransifex** [comment]
Closing this one, as is the same as #183 .

If something come up, we can reopen it.
