### ISSUE TITLE
[React] Update useT to allow specifying the tx instance to use

### ISSUE THREAD

**Issue by unkillbob** [transifex/transifex-javascript#182]
**What**
I would like a mechanism to be able to specify the `tx` instance used to translate by `useT` so I can create reusable custom hooks containing translations hosted in a shared library (essentially the hook equivalent to [what `TXProvider` enables with components](https://developers.transifex.com/docs/react-sdk#txprovider-provider)).

**Why**
At our organisation there are some lists of translations (e.g. map of currency code to translated currency name) that are hosted in shared libraries to be used across multiple React applications.

Initially we tried creating some custom hooks in these shared libraries and using `useT` to do the translation within the hooks. However this didn't work as the `t` returned by `useT` was associated with the `tx` instance for the application, not for the shared library. For components hosted in these shared libraries we can wrap them with `TXProvider` to ensure they are internally accessing the correct `tx` instance when translating, however there doesn't appear to be an equivalent mechanism for hooks.

**Potential Solution**
One possible way to solve this would be:
1. Add an optional argument to `useT` to allow passing in a specific `tx` instance
2. Change `translateWithElements` to pass in a `tx` instance as the 3rd argument instead of a reference to the context

I've employed a workaround that is very similar to proposed solution (a clone of `useT` that just uses `tx.t` directly though as I can't access `translateWithElements`) and it seems to be working well. If the proposed solution seems reasonable I'm also happy to submit a PR.

**Comment by nbasili** [comment]
@unkillbob Apologies for taking so long to reply.

I've opened a related PR for your request, if you'd like to take a look: https://github.com/transifex/transifex-javascript/pull/205 

The scope has increased to the other hooks as well.

**Comment by unkillbob** [comment]
thanks @nbasili, I took a look and it looked good to me!

**Comment by nbasili** [comment]
Fix has been released on `@transifex/native@7.0.1`
