### ISSUE TITLE
[Bug] CLI push silently fails for Angular 15+ self-closing-tags

### ISSUE THREAD

**Issue by tomcek112** [transifex/transifex-javascript#193]
**Current Behavior**
Running `txjs-cli push` silently fails for Angular templates containing [self-closing-tags](https://github.com/angular/angular/pull/48535). No translatable phrases are picked up and the process succeeds.

**Expected Behavior**
The translatable phrases are picked up and pushed to Transifex Cloud

**Steps to Reproduce**
1. Add any translatable string to an Angular template using the self-closing-tag syntax (e.g. `<my-component />`)
2. Run `txjs-cli push` in the directory containing the template

**Possible Solution**
Self-closing-tags were only introduced in Angular 15. The `angular-html-parser` version (`@1.8.0`) used in this package is much older so it errors out with `Only void and foreign elements can be self closed "my-component"`.
One possible solution would be to upgrade `angular-html-parser@latest`. This should fix the issue but might have implications I'm not aware of. 

Related line for the silent fail can be found here: https://github.com/transifex/transifex-javascript/blob/f63c4299df338018cfdfb66682ad2d56be1b39a5/packages/cli/src/api/parsers/angularHTML.js#L153-L154

I'll be happy to open a related PR.

**Comment by pablotransifex** [comment]
@tomcek112 Hello and thank you for your feedback! If you have something ready please open a PR and we will check it.

**Comment by tomcek112** [comment]
@pablotransifex Thanks for the quick reply. The reason I opened this issue instead of a PR directly is that `angular-html-parser` only ships as an ES module from version `<2.0.0`. 
As far as I can tell this is a problem for the `@transifex/cli` project since it exclusively uses CommonJS modules. 

The proper fix here would be to move `@transifex/cli` over to ESM (which you'll probably want to do anyway) but this kind of contribution doesn't seem like something that should come from me. 

The only other two options I see are:
1. add a transpiler (e.g. Babel or even TS) and use it to transpile CJS to ESM and vice-versa
2. make the encapsulating `parseHTMLTemplateFile` function `async` so we can dynamically `import('angular-html-parser')`. However, this is more of a hack and might cause other issues.

In any case, I don't think I should be making the decision here so I'll be happy to hear your thoughts!

**Comment by tomcek112** [comment]
Scratch all that, I just stumbled upon the fact that `angular-html-parser` supports passing the `canSelfClose` option to the Angular parser directly since `1.0.0`. I didn't even know that options already existed back then 😅 

Seeing that the linked PR that introduced self-closing-tags in Angular 15 pretty much just defaults this to `true`, it should be safe for us to do the same here. 

I would still love to see an upgrade to `angular-html-parser` and probably better error handling whenever the parser fails but to move this specific issue ahead I'll open a PR just setting this flag.

**Comment by pablotransifex** [comment]
Perfect, I was wondering if we could avoid all the big refactoring as well! @nbasili Will send you instructions related to our CLA policy for collaborators as soon as possible, in order to move on with this PR. Again, thank you very much!

**Comment by tomcek112** [comment]
Cool yeah, no worries! Do I have to sign the CLA policy again, though? This is not my first contribution 😅 (#171)

**Comment by nbasili** [comment]
> Cool yeah, no worries! Do I have to sign the CLA policy again, though? This is not my first contribution 😅 (#171)

No need, you have already signed it.
