### ISSUE TITLE
[Bug] upload and download functions are missing from .d.ts

### ISSUE THREAD

**Issue by sherlock1982** [transifex/transifex-javascript#198]
**Current Behavior**
upload/download functions are missing

**Expected Behavior**
upload/download function should be accessible as per documentation

**Steps to Reproduce**
As per documentation this call should be possible:

`await transifexApi.ResourceStringsAsyncUpload.upload({
  resource,
  content,
});`

transifex.Api.d.ts doesn't contain this function

**Comment by nbasili** [comment]
Fix has been released on `@transifex/api@7.0.1`
