### ISSUE TITLE
[Bug] fetchTimeout does not handle network latency

### ISSUE THREAD

**Issue by edsrzf** [transifex/transifex-javascript#200]
**Current Behavior**
If I specify `fetchTimeout` in the `init` method, the timeout only comes into effect when the request fails. If the request is simply slow, due to network latency, the timeout doesn't trigger.

**Expected Behavior**
The timeout should be triggered when the fetch request is slow.

**Steps to Reproduce**
* Initialize Transifex Native using a `fetchTimeout`.
* Simulate network latency through a proxy or other developer tools. The latency must be longer than the configured timeout.
* Observe that translation-fetching continues past the timeout.

**Possible Solution**
Add a timeout to the `axios.Get` call.

**Possible Implementation**
I would use an Axios `AbortController` with a timeout based on `fetchTimeout`, as documented on this page: https://axios-http.com/docs/cancellation

**Comment by nbasili** [comment]
This is handled as part of this PR: https://github.com/transifex/transifex-javascript/pull/204

**Comment by nbasili** [comment]
Fix has been released on `@transifex/native@7.0.1`
