### ISSUE TITLE
[Bug] Missing "t" function on txNative type / Required Config for "CreateNativeInstance" 

### ISSUE THREAD

**Issue by aarr0n** [transifex/transifex-javascript#210]
**Current Behavior**
- The `t` (translate) function is [missing from the defined `txNative` type](https://github.com/transifex/transifex-javascript/blob/master/packages/native/src/index.d.ts#L56). It's bound [when creating a new native instance](https://github.com/transifex/transifex-javascript/blob/master/packages/native/src/index.js#L12).
- [The `createNativeInstance` type](https://github.com/transifex/transifex-javascript/blob/master/packages/native/src/index.d.ts#L168C19-L168C39) expects a mandatory `initOptions` / `ITranslationConfig` type to be passed. But I would suggest this to be optional since [its not actually required](https://github.com/transifex/transifex-javascript/blob/master/packages/native/src/index.js#L10-L16).

**Expected Behavior**
- I expect to see the `t` function defined on the `txNative` type.
- I expect to see the `ITranslationConfig` argument of `createNativeInstance` to be optional.

**Steps to Reproduce**
```ts
// Missing `t` function on `TxtNative`
const instance = createNativeInstance({ token: '123', filterTags: 'example' }) 
const t = txInstance.t // TS Error: Property 't' does not exist on type 'TxNative'
```
```ts
// Mandatory `ITranslationConfig` for `createNativeInstance`
const instance = createNativeInstance() // TS Error: An argument for 'initOptions' was not provided.
```
**Possible Solution**
- Add `t` function to `txtNative` class
- Update `createNativeInstance` and make `ITranslationConfig` optional

**Possible Implementation**
index.d.ts
```ts
export class TxNative implements ITranslationConfig {
  // ...
  t(sourceString: string, params?: ITranslateParams): string;
}

export function createNativeInstance(initOptions?: ITranslationConfig): TxNative;

```

**Comment by nbasili** [comment]
Fix has been released on `@transifex/native@7.0.1`
