### ISSUE TITLE
useT call fails because prototype differs from the one shown in docs

### ISSUE THREAD

**Issue by arturtamborski** [transifex/transifex-javascript#48]
Hi,

I'm trying to integrate this library in our project using transifex & react, but we were stopped by the difference in docs and what's actually written down in the code.

Currently, `useT` expects two arguments to call it: `_str` and `props`.
https://github.com/transifex/transifex-javascript/blob/211dee726c2b1365c43de6e860b3d6803dcdc3d7/packages/react/src/hooks/useT.js#L20

Readme suggests, that one should call `useT` without passing the second argument here
https://github.com/transifex/transifex-javascript/blob/211dee726c2b1365c43de6e860b3d6803dcdc3d7/packages/react/README.md#uset-hook

but this does not work, because without passing second argument (even just empty object) the `props` will end up with `undefined` value, will pass it over to `translateWithElements()`, and, in the end will fail on `Object.entries()` here:https://github.com/transifex/transifex-javascript/blob/211dee726c2b1365c43de6e860b3d6803dcdc3d7/packages/react/src/utils/translateWithElements.jsx#L20

We did discover a simple workaround - pass over empty `{}` every time `useT()` is called, but it's bit annoying to deal with it that way, like so:
```js
const translated = useT('Hello', {});
return <span>{translated}</span>
```

Will you consider fixing this issue? Or maybe we're doing something wrong here? Any help would be very appreciated.

Thank you.

**Comment by codegaze** [comment]
Hello @arturtamborski. Thanks for reporting this issue.
Updating to the latest released version should solve this and there is no need to add the empty `{}` in your `useT` function.

**Comment by arturtamborski** [comment]
Thank you!
