### ISSUE TITLE
[bug] Multiline strings using backticks don't push to Transifex

### ISSUE THREAD

**Issue by wgyt** [transifex/transifex-javascript#57]
## How to reproduce:
Make a file with the following, I think this could also happen with other multiline strings
```js
import { t } from "@transifex/native";
t(`Commands:
> start: starts 1host.js
  >> args: directory: changes the directory
  >> usage: 1host start < directory (optional) >
> config: changes the config file
  >> args: directory: changes the directory
  >> usage: 1host config < directory (optional) >
`);
```
Then run Transifex CLI
## What happened?
Everything except the multiline string was pushed
## Why is this problematic?
I use multiline strings using backticks so my code doesn't include \n and so it looks cleaner.
## Expected behavior
The multiline string is pushed to Transifex
## Versions
Node v14.16.1
Transifex CLI v0.12.1
Transifex Native v0.12.1

**Comment by arturtamborski** [comment]
Hi,

template literals are not supported:
https://github.com/transifex/transifex-javascript/blob/master/packages/cli/src/api/extract.js#L212 
https://github.com/transifex/transifex-javascript/blob/master/packages/cli/test/fixtures/variables.js#L27

Your best bet (besides implementing this feature) would be to use escape sequences:

example code:
```js
let x = `
something something
another line
that works just fine
`;

console.log(x);


let y = "\
something something \n\
another line \n\
that works just fine \n\
";

console.log(y);

```

output:
```

something something
another line
that works just fine

something something 
another line 
that works just fine 

```

**Comment by wgyt** [comment]
Closing this issue because the comment above solved my issue.
