### ISSUE TITLE
Support for custom MessageFormat options

### ISSUE THREAD

**Issue by BasixKOR** [transifex/transifex-javascript#60]
It seems like Transifex Native uses MessageFormat under the hood, and using default options is sometimes not enough for some advanced use cases.

For example in Korean, MessageFormat custom formatter can be used for Josa processing, which is common problem for Korean localization. (You can think of `a/an` of English as an example, but it is used more than just articles.)

Note: `messageformat` is renamed to `@messageformat/core`, so it would be nice to replace it while adding this feature. I'm 100% willing to implement this.

**Comment by nbasili** [comment]
@BasixKOR Thanks for that, can you please check if [this PR](https://github.com/transifex/transifex-javascript/pull/62) does what you are looking for? 

It upgrades to `@messageformat/core` and allows you to override the default settings with a custom `stringRenderer` abstract class.

**Comment by BasixKOR** [comment]
Thanks for your quick reply! And yes that looks like exactly what I was looking for.

**Comment by nbasili** [comment]
Part of [v0.13.0](https://github.com/transifex/transifex-javascript/releases/tag/v0.13.0) release.
