### ISSUE TITLE
CLI assumes StringLiteral for _str

### ISSUE THREAD

**Issue by BasixKOR** [transifex/transifex-javascript#61]
It should be possible to use string concateration and const variable reference as useT call does, but appearently it doesn't. Checking for `JSXExpressionContainer` and calling `findDeclaredValue` will implement this missing feature pretty quick.

**Comment by BasixKOR** [comment]
Workaround: use `useT` to retrive translation, and reference it inside your JSX.

**Comment by nbasili** [comment]
@BasixKOR Fix on this [PR](https://github.com/transifex/transifex-javascript/pull/63).

**Comment by BasixKOR** [comment]
Thank you so much! :D

**Comment by nbasili** [comment]
Part of [v0.13.0](https://github.com/transifex/transifex-javascript/releases/tag/v0.13.0) release.
