### ISSUE TITLE
Improve TypeScript typings

### ISSUE THREAD

**Issue by BasixKOR** [transifex/transifex-javascript#64]
Currently this project seems like using checkJs to check the types of the code, but when user downloads the package and try to use it there are no JSDoc left in the compiled module, so TypeScript infers the type of all the exported memebers as `any`.

I think this could be improved by enabling to emit declaration file in tsconfig. This issue doesn't seem to affect Angular users, although I haven't actually tested that.

**Comment by justjoeyuk** [comment]
This is something that would be great.

**Comment by nbasili** [comment]
Closing this issue as it is rather old. Transifex Native is not written in TypeScript, so unsure how this can be tackled to be honest.

**Comment by BasixKOR** [comment]
There are many resources on how this can be done, i.e. https://stackoverflow.com/a/53710641/4154321. Probably looking around JavaScript packages providing TS types would be a great place to get started.

**Comment by Etchelon** [comment]
@nbasili any ideas why the typings included in your packages are all basically resolved to any?

<img width="780" alt="image" src="https://user-images.githubusercontent.com/4141889/204024172-8faaa3dc-5055-4e9c-8113-5c2f6b15f83a.png">

**Comment by nbasili** [comment]
Yes, because this file is not automatically generated. It was added as a temp solution until we figure out something better :/
