### ISSUE TITLE
How to disable automatic locale detection and redirect

### ISSUE THREAD

**Issue by localjo** [transifex/transifex-javascript#98]
We would like to disable automatic locale detection and redirection in our React app using Transifex Native. I see that with Transifex Live, this is possible by setting:

```
window.liveSettings = {
  detectlang: false,
}
```

But I can't find the documentation for how to disable this while using Transifex Native. Is it possible? If so, what is the best way to do it?

**Comment by nbasili** [comment]
@localjo Transifex Native does not autodetect the language. The developer is responsible for setting the language using the `tx.setCurrentLocale(..)` method. Can you please clarify how auto detection works in your case?

**Comment by localjo** [comment]
Thank you for the clarification. I see now that what was happening in our case is that the `locale` we are passing to `setCurrentLocale` is coming from Next.js, and [Next.js has automatic locale detection](https://nextjs.org/docs/advanced-features/i18n-routing#automatic-locale-detection) that is causing the redirect.
