### ISSUE TITLE
Incorrect types for resource strings downloads and uploads

### ISSUE THREAD

**Issue by psmyrek** [transifex/transifex-javascript#99]
Hi! I think I found a bug in the `@transifex/api` package for Node.js.

I'm using the `@transifex/api` in version 2.1.0. I'm trying to create a source file download action:

```js
const {transifexApi} = require('@transifex/api');

transifexApi.setup(/* token */);

const resourceStringAsyncDownload = await transifexApi.ResourceStringAsyncDownload.create({
    attributes: /* attributes */,
    relationships: /* relationships */,
    type: 'resource_strings_async_downloads'
});
```

but I'm receiving the following error:

```
Error: Received type 'resource_strings_async_downloads', expected 'resource_string_async_downloads'
```

When I change the type to the suggested one `resource_string_async_downloads`, I have another error:

```
JsonApiException: <JsonApiError: 404 - URL `/ resource_string_async_downloads` does not refer to an existing endpoint
```

I think there is a typo here: https://github.com/transifex/transifex-javascript/blob/6dcede2ab419bbf95126ed61f58c838e7cae1daa/packages/api/src/transifexApi.js#L43
The resource type should be `resource_strings_async_downloads` (`string` → `strings`).

There is another incorrect type in the same file a few lines below: https://github.com/transifex/transifex-javascript/blob/6dcede2ab419bbf95126ed61f58c838e7cae1daa/packages/api/src/transifexApi.js#L48
The type for uploading a new source file for a resource should be `resource_strings_async_uploads`.

**Comment by nbasili** [comment]
@psmyrek Thanks for spotting this. We released `2.1.1` version of the package with a fix in the endpoint. Can you please verify it works on your side?

**Comment by psmyrek** [comment]
Thanks for quick update. Downloading resource strings in `2.1.1` works great.
But it looks like there is still a typo for async upload:

https://github.com/transifex/transifex-javascript/blob/9426d2f27fd11826bfe63843f7b6f34b558aa03a/packages/api/src/transifexApi.js#L48

Shouldn't it be `resource_strings_async_uploads`?

**Comment by nbasili** [comment]
Oups, `2.1.2` to the rescue 😅

**Comment by psmyrek** [comment]
Great, thanks 👍🏻
